// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: member.proto

package com.zx.member.service;

public final class Member {
  private Member() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_member_SignOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_member_SignOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_member_SignOnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_member_SignOnResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014member.proto\022\006member\"3\n\rSignOnRequest\022" +
      "\020\n\010userName\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\" \n\016S" +
      "ignOnResponse\022\016\n\006userId\030\001 \001(\r2H\n\rMemberS" +
      "ervice\0227\n\006SignOn\022\025.member.SignOnRequest\032" +
      "\026.member.SignOnResponseB\031\n\025com.zx.member" +
      ".serviceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_member_SignOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_member_SignOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_member_SignOnRequest_descriptor,
        new String[] { "UserName", "Password", });
    internal_static_member_SignOnResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_member_SignOnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_member_SignOnResponse_descriptor,
        new String[] { "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
