// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: member.proto

package com.zx.member.service;

public interface SignOnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:member.SignOnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
