// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: member.proto

package com.zx.member.service;

public interface SignOnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:member.SignOnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 userId = 1;</code>
   */
  int getUserId();
}
